name: CheckMkDocsBuild
on:
  # Trigger the workflow on a new pull request on master
  pull_request_target:
    branches:
      - main

jobs:
  build-docs-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Allow to move dotfiles
        run: |
          # move also dotfile with *
          shopt -s dotglob

      - name: Clone XCM SDK MKDocs
        run: |
          # clone mkdocs repo locally
          git clone https://${{ secrets.REPO_SCOPED_TOKEN }}@github.com/eshaben/xcm-sdk-mkdocs.git

      - name: Install pip requirements
        run: |
          cd xcm-sdk-mkdocs
          # upgrade pip
          pip3 install --upgrade pip setuptools==65.7.0
          # install dependencies quietly
          pip3 install -r requirements.txt &> /dev/null && echo "Dependencies installed" || echo "Error while installing dependencies"

      - name: Build mkdocs
        run: |
          cd xcm-sdk-mkdocs
          # change destination build folder in mkdocs YAML to local site/
          sed -i "s/'site_dir'.*/'site_dir': 'site'/" mkdocs.yml
          # build project
          python3 -m mkdocs build